import { makeStyles} from "@material-ui/core/styles";



export default makeStyles({
    root: {
        flexGrow: 1,
      },
      ostello_logo: {
        fontStyle: "normal",
        fontWeight: "bold",
        FontSize: "22.6787px",
        fontFamily: "Gotham-bold",
        width: "60.66px",
        color: "#6074E3",
        marginLeft: "9rem",
        marginTop: "2.2rem",
      },
      Blog_title: {
        fontFamily: "Gotham-Light",
        fontStyle: "normal",
        fontWeight: "bold",
        fontSize: "16px",
        marginTop: "23px",
        marginLeft: "2.8rem",
      },
      tell_us: {
        fontFamily: "Gotham-Light",
        fontStyle: "normal",
        fontWeight: "bold",
        fontSize: "16px",
        marginTop: "42px",
        marginLeft: "2.9rem",
      },
      cover_img: {
        fontFamily: "Gotham-Light",
        fontStyle: "normal",
        fontWeight: "bold",
        fontSize: "16px",
        marginTop: "12px",
        marginLeft: "3rem",
      },
      content_img: {
        fontFamily: "Gotham-Light",
        fontStyle: "normal",
        fontWeight: "bold",
        fontSize: "16px",
        marginLeft: "3rem",
      },
      publish_btn: {
        width: "179px",
        backgroundColor: "#6074E3",
        color: "#fff",
        marginLeft: "0.3rem",
        height: "49px",
        fontSize: "19.5085px",
        marginTop: "2.8rem",
      },
      text_title_blog: {
        fontFamily: "Gotham-bold",
        backgroundColor: "#FFFFFF",
        borderRadius: "12px",
        width: "881px",
        marginLeft: "3px",
      },
      story_text: {
        marginLeft: "0.3rem",
        width: "881px",
        height: 181,
        borderRadius: "12px",
      },
      cover_btn_icon: {
        position: "absolute",
        marginTop: "12px",
        marginLeft: "0.3rem",
        width: "69px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0px 4px 12px rgba(0, 0, 0, 0.16)",
        borderRadius: "12px",
      },
      content_btn_icon: {
        position: "absolute",
        marginTop: "21px",
        marginLeft: "0.3rem",
        width: "69px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0px 4px 12px rgba(0, 0, 0, 0.16)",
        borderRadius: "12px",
      },
      paper: {
        fontSize: "38px",
        fontFamily: "Calibri",
        color: "#646464",
        textAlign: "center",
        fontWeight: "bolder",
        display: "flex",
        flexDirection: "column",
      },
      Blog_headeing: {
        fontSize: "35px",
        fontFamily: "Calibri",
        fontWeight: "bold",
        color: "#6074E3",
      },
      logo_img: {
        marginLeft: "14rem",
        width: "30.88px",
        marginTop: "30px",
        cursor: "pointer",
        fontSize: "62px",
      },
      input: {
        display: "none",
      },
})